CHANNELS = {
    "antauro_tv": {
        "id": "antauro_tv",
        "name": "AntauroTV",
        "emoji": "🟢",
        "engine": "antauro_engine",
        "entry_point": "generar_clips",
        "description": "Extrae clips de Antauro Humala — propuestas, denuncias y visión de país",
        "hashtags": {
            "constituc": "#NuevaConstitución",
            "nacional": "#Nacionalismo",
            "etnocacer": "#Etnocacerismo",
            "andina": "#IdentidadAndina",
            "indígena": "#IdentidadAndina",
            "indigena": "#IdentidadAndina",
            "soberan": "#Soberanía",
            "neoliberal": "#AntiNeoliberalismo",
            "corrupción": "#Corrupción",
            "corrupcion": "#Corrupción",
            "ejército": "#FuerzasArmadas",
            "ejercito": "#FuerzasArmadas",
            "perú": "#Perú",
            "peru": "#Perú",
            "justicia": "#JusticiaSocial",
            "economía": "#EconomíaNacional",
            "economia": "#EconomíaNacional",
            "fujimori": "#Fujimorismo",
            "tahuantinsuyo": "#Tahuantinsuyo",
            "locumbazo": "#Locumbazo",
            "andahuaylazo": "#Andahuaylazo",
            "rebelión": "#Rebelión",
            "rebelion": "#Rebelión",
            "prensa": "#PrensaBasura",
            "identidad": "#IdentidadNacional",
            "patria": "#Patria",
            "reservista": "#Reservistas",
            "veterano": "#Veteranos",
            "pena de muerte": "#PenaCapital",
            "toledo": "#ToledoTraidor",
        },
        "default_hashtags": ["#AntauroHumala", "#Perú"],
        "prompt_context": "Antauro Humala — líder etnocacerista peruano",
    },
    "deepskill": {
        "id": "deepskill",
        "name": "DeepSkill",
        "emoji": "🔵",
        "engine": "deepskill_engine",
        "entry_point": "extract_clips",
        "description": "Clips de tecnología, programación y contenido interesante (30s–150s)",
        "hashtags": {
            "python": "#Python",
            "javascript": "#JavaScript",
            "typescript": "#TypeScript",
            "rust": "#RustLang",
            "go ": "#GoLang",
            "golang": "#GoLang",
            "react": "#ReactJS",
            "node": "#NodeJS",
            "docker": "#Docker",
            "kubernetes": "#Kubernetes",
            "api": "#API",
            "algorithm": "#Algoritmos",
            "data structure": "#EstructurasDeDatos",
            "machine learning": "#MachineLearning",
            "deep learning": "#DeepLearning",
            "ai ": "#InteligenciaArtificial",
            "inteligencia artificial": "#InteligenciaArtificial",
            "neural": "#RedesNeuronales",
            "backend": "#Backend",
            "frontend": "#Frontend",
            "fullstack": "#FullStack",
            "devops": "#DevOps",
            "cloud": "#CloudComputing",
            "aws": "#AWS",
            "azure": "#Azure",
            "sql": "#SQL",
            "database": "#BaseDeDatos",
            "compiler": "#Compiladores",
            "linux": "#Linux",
            "git": "#Git",
            "open source": "#OpenSource",
            "carrera": "#CarreraTech",
            "trabajo": "#TrabajoTech",
            "salario": "#SalarioTech",
            "entrevista": "#EntrevistasTech",
            "startup": "#Startup",
            "system design": "#SystemDesign",
            "arquitectura": "#ArquitecturaSoftware",
            "testing": "#Testing",
            "seguridad": "#Ciberseguridad",
            "blockchain": "#Blockchain",
        },
        "default_hashtags": ["#Programación", "#DevTips"],
        "prompt_context": "contenido tech para programadores",
    },
    "general": {
        "id": "general",
        "name": "Clip Rápido",
        "emoji": "⚡",
        "engine": "generic_engine",
        "entry_point": "extract_clips",
        "description": "Extrae clips virales de cualquier tema (noticias, fútbol, cursos, política, etc.)",
        "hashtags": {},
        "default_hashtags": ["#Clips", "#Viral"],
        "prompt_context": "contenido general para cualquier tema",
    },
}


def get_channel(channel_id: str) -> dict | None:
    return CHANNELS.get(channel_id)


def list_channels() -> list[dict]:
    return list(CHANNELS.values())
